# NUMPY

In [28]:
import numpy as np

# Dataset
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KDR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_Bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find the country index with the maximum gold medals
max_gold_index = np.argmax(np_olympic_country_gold)

# 2. Print the country with the maximum gold medals
country_with_max_gold = np_olympic_country[max_gold_index]
print("Country with the most gold medals:", country_with_max_gold)

# 3. Find countries with more than 20 gold medals
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]
print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)

# 4. Evaluate the dataset and print the medals
# Print each country name with the number of gold medals
for i in range(len(np_olympic_country)):
    print(np_olympic_country[i], "Gold:", np_olympic_country_gold[i])

# Print each country name with the total number of medals
for i in range(len(np_olympic_country)):
    total_medals = np_olympic_country_gold[i] + np_olympic_country_silver[i] + np_olympic_country_Bronze[i]
    print(np_olympic_country[i], "Total Medals:", total_medals)


Country with the most gold medals: US
Countries with more than 20 gold medals: ['GBR' 'China' 'RUS' 'US']
GBR Gold: 29
China Gold: 38
RUS Gold: 24
US Gold: 46
KDR Gold: 13
JPN Gold: 7
GER Gold: 11
GBR Total Medals: 65
China Total Medals: 88
RUS Total Medals: 81
US Total Medals: 103
KDR Total Medals: 28
JPN Total Medals: 38
GER Total Medals: 36


In [27]:
# 1.Create a 3x3x3 array with random values 
import numpy as np
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.19587012 0.05451822 0.83795196]
  [0.08182621 0.21038779 0.52460484]
  [0.44323983 0.90121789 0.22318969]]

 [[0.86334649 0.87375259 0.652342  ]
  [0.99604801 0.20740641 0.82188354]
  [0.2646837  0.71993288 0.6945084 ]]

 [[0.23372203 0.65394858 0.01549715]
  [0.68573183 0.9944504  0.3739049 ]
  [0.81181296 0.86434937 0.86155584]]]


In [2]:
#2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, and 4 just below the diagonal
values = [1, 2, 3, 4]
for i in range(1, 5):
    matrix[i, i - 1] = values[i - 1]

# Print the resulting matrix
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [3]:
#3.Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with alternating 1s
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

# Print the resulting checkerboard matrix
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#4. Normalize a 5x5 random matrix
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
mean = random_matrix.mean()
std_dev = random_matrix.std()
normalized_matrix = (random_matrix - mean) / std_dev

# Print the original and normalized matrices
print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.48451283 0.1815465  0.64630449 0.07472855 0.89694141]
 [0.9390893  0.04906888 0.20663142 0.19079634 0.56307932]
 [0.81213326 0.46942664 0.34102801 0.85272928 0.29965024]
 [0.72673067 0.94215386 0.91545289 0.56970318 0.89459911]
 [0.68910077 0.23751879 0.5382977  0.86597336 0.10216503]]

Normalized Matrix:
[[-0.18269991 -1.18797181  0.35414063 -1.54240422  1.18577844]
 [ 1.32562927 -1.62754551 -1.10473762 -1.15727996  0.07799138]
 [ 0.9043767  -0.23275737 -0.65879659  1.03907825 -0.79609206]
 [ 0.62100256  1.33579778  1.24720133  0.09997     1.17800646]
 [ 0.49614288 -1.00225028 -0.00423646  1.08302342 -1.45136731]]


In [5]:
#5. How to find common values between two arrays?
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

# Print the common values
print("Common values:", common_values)

Common values: [3 4 5]


In [6]:
#6.How to get the dates of yesterday, today and tomorrow?
import numpy as np
import datetime

# Get the current date
current_date = datetime.date.today()

# Calculate the dates of yesterday and tomorrow
yesterday = current_date - datetime.timedelta(days=1)
tomorrow = current_date + datetime.timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", current_date)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [8]:
#7. Consider two random array A and B, check if they are equal
import numpy as np

# Create two random arrays, A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the two arrays are equal
are_equal = np.array_equal(A, B)

# Print the result
if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


In [13]:
#8.Create random vector of size 10 and replace the maximum value by 0
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector_with_zero = random_vector.copy()  
random_vector_with_zero[max_index] = 0

print("Original random vector:")
print(random_vector)

print("\nRandom vector with maximum value replaced by 0:")
print(random_vector_with_zero)


Original random vector:
[0.38761433 0.24387532 0.88779728 0.75869478 0.02228492 0.24992895
 0.38148417 0.60267946 0.74773353 0.63647928]

Random vector with maximum value replaced by 0:
[0.38761433 0.24387532 0.         0.75869478 0.02228492 0.24992895
 0.38148417 0.60267946 0.74773353 0.63647928]


In [24]:
import numpy as np

# Create an example array
my_array = np.array([1, 2, 3, 4, 5])

# Using a loop to print each value
for value in my_array:
    print(value)

1
2
3
4
5


In [14]:
#10.Subtract the mean of each row of a matrix
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
normalized_matrix = matrix - row_means

# Print the original and normalized matrices
print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix (Mean Subtracted from Each Row):")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Matrix (Mean Subtracted from Each Row):
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [16]:
#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5, 6])

# Second vector of indices
indices_vector = np.array([1, 3, 2, 4])

# Create a copy of the given vector to avoid modifying the original
result_vector = given_vector.copy()

# Add 1 to the elements indexed by the second vector
result_vector[indices_vector] += 1

print("Original vector:")
print(given_vector)

print("\nResult vector with 1 added to selected indices:")
print(result_vector)


Original vector:
[1 2 3 4 5 6]

Result vector with 1 added to selected indices:
[1 3 4 5 6 6]


In [17]:
#12.How to get the diagonal of a dot product?
import numpy as np

# Create two matrices A and B (replace with your own matrices)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal of the Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


In [26]:
#13.How to find the most frequent value in an array?
import numpy as np

# Create a NumPy array (replace with your own array)
arr = np.array([7, 4, 5, 3, 3, 6, 5, 8, 1, 5, 1, 1, 8, 7, 4, 5, 8, 7, 3, 2, 3, 6, 
                1, 5, 3, 3, 7, 5, 0, 3, 8, 7, 1, 4, 1, 4, 1, 1, 1, 6, 6, 8, 6, 8,3, 4, 4, 7, 8, 0])

# Use numpy.unique to get unique values and their counts
unique_values, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[max_count_index]

print("Array:", arr)
print("Most frequent value:", most_frequent_value)


Array: [7 4 5 3 3 6 5 8 1 5 1 1 8 7 4 5 8 7 3 2 3 6 1 5 3 3 7 5 0 3 8 7 1 4 1 4 1
 1 1 6 6 8 6 8 3 4 4 7 8 0]
Most frequent value: 1


In [20]:
#14.How to get the n largest values of an array
import numpy as np

# Create a NumPy array (replace with your own array)
arr = np.array([4, 2, 7, 1, 9, 5, 8, 3, 6])

# (e.g., n = 3)
n = 3

# Use numpy.partition to partially sort the array
# The n largest values will be on the right side of the partitioned array
partially_sorted = np.partition(arr, -n)

# Slice the last n elements to get the n largest values
n_largest_values = partially_sorted[-n:]

print("Array:", arr)
print(f"{n} Largest Values:", n_largest_values)


Array: [4 2 7 1 9 5 8 3 6]
3 Largest Values: [7 8 9]


In [21]:
#15.How to create a record array from a regular array
import numpy as np

# Create a regular array with data
regular_array = np.array([(1, 'priya', 22),
                          (2, 'janu', 24),
                          (3, 'vinay', 18)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Print the regular array
print("Regular Array:")
print(regular_array)

# Convert the regular array to a record array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

# Print the record array
print("\nRecord Array:")
print(record_array)


Regular Array:
[(1, 'priya', 22) (2, 'janu', 24) (3, 'vinay', 18)]

Record Array:
((1, 'priya', 22), (2, 'janu', 24), (3, 'vinay', 18))


In [22]:
#16. How to swap two rows of an array?
import numpy as np

# Create a sample 2D NumPy array (replace with your own array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Indices of the rows you want to swap (0-based index)
row1_index = 0
row2_index = 2

# Swap the rows using array slicing and indexing
array[[row1_index, row2_index]] = array[[row2_index, row1_index]]

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [23]:
#17. Write python code to reshape to the next dimension of numpy array
import numpy as np

# Create the original 2D array
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape the array to the next dimension (3D)
reshaped_array = x.reshape((x.shape[0], x.shape[1], 1))

print("Original 2D Array:")
print(x)

print("\nReshaped 3D Array:")
print(reshaped_array)


Original 2D Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped 3D Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
